services:
    postgres-db:
        image: pgvector/pgvector:pg18-trixie
        container_name: ${POSTGRES_CONTAINER_NAME}
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - ./${POSTGRES_CONTAINER_NAME}-data:/var/lib/postgresql
        user: "${HOST_UID}:${HOST_GID}"
        networks:
            - specified_network

    postgres-pgadmin:
        image: dpage/pgadmin4:9.10.0
        container_name: ${POSTGRES_CONTAINER_NAME}-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "True"
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - postgres-db
        volumes:
            - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - specified_network

    postgres-backup:
        image: alpine:3.23
        container_name: ${POSTGRES_CONTAINER_NAME}-backup
        depends_on:
            - postgres-db
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backups:/backups
            - ./backup.key:/backup.key:ro
            - ./.env:/.env:ro
            - ./backup.sh:/backup.sh:ro
        working_dir: /
        entrypoint: ["sh", "-c"]
        command: '
            "apk add --no-cache
            docker-cli
            postgresql18-client
            gzip
            openssl
            aws-cli
            bash
            && sleep infinity"
            '
        labels:
            ofelia.enabled: "true"
            ofelia.job-exec.postgres-backup-job.schedule: ${BACKUP_SCHEDULE}
            ofelia.job-exec.postgres-backup-job.command: "/backup.sh /backups"
            ofelia.job-exec.postgres-backup-job.no-overlap: "true"
        networks:
            - specified_network

volumes:
    pgadmin-data:
        name: ${POSTGRES_CONTAINER_NAME}-pgadmin-data
        driver: local

networks:
    specified_network:
        name: ${DOCKER_NETWORK_NAME}
        driver: bridge
        external: ${DOCKER_EXTERNAL_NETWORK}
